#!/usr/bin/env bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
filter=""
dry="0"

cd $script_dir
scripts=$(find runs -maxdepth 1 -mindepth 1 -executable -type f)

while [[ $# -gt 0 ]]; do
	if [[ $1 == "--dry" ]]; then
		dry="1"
	else
		filter="$1"
	fi
	shift
done

log () {
	if [[ $dry == "1" ]]; then
		echo "[DRY_RUN]: $@"
	else
		echo "$@"
	fi
}

execute () {
	log "executing: $@"
	if [[ $dry == "1" ]]; then
		return
	fi

	"$@"
}

log "run: $script_dir -- filter=$filter"

for script in $scripts; do
	if echo "$script" | grep -qv "$filter"; then
		log "filtered: $filter -- $script"
		continue
	fi
	execute ./"$script"
done
