#!/usr/bin/env bash

#get dependencies
sudo apt-get install libevent-dev ncurses-dev build-essential bison pkg-config autoconf automake autotools-dev

#get tmux
git clone --depth 1 https://github.com/tmux/tmux.git $HOME/personal/tmux
cd $HOME/personal/tmux
sh autogen.sh
./configure
make && sudo make install
